CREATE SEQUENCE SEQ_JOB START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_STAFF START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_CUSTOMER START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_VENDOR START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE SEQ_LCATEGORY START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_MCATEGORY START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_SCATEGORY START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE SEQ_STOCK START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_STOCK_DETAIL START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE SEQ_SALE START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_SALE_DETAIL START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE SEQ_PAYMENT START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PAYMENT_DETAIL START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE SEQ_ORDER_DETAIL START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE SEQ_EVENT START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_EVENT_PRODUCT START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_EVENT_TYPE START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE SEQ_DISCARD START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_DISCARD_DETAIL START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE SEQ_SETTLEMENT START WITH 1 INCREMENT BY 1;
------------------------------
INSERT INTO TBL_JOB
VALUES
(
SEQ_JOB.NEXTVAL,
'점장'
);
--
INSERT INTO TBL_VENDOR
VALUES
(
SEQ_VENDOR.NEXTVAL,
'롯데칠성',
'김대리',
'서울시 송파구',
'02-111-2222'
);
--
INSERT INTO TBL_LCATEGORY
VALUES
(
SEQ_LCATEGORY.NEXTVAL,
'식품'
);
--
INSERT INTO TBL_MCATEGORY
VALUES
(
SEQ_MCATEGORY.NEXTVAL,
1,
'음료'
);
--
INSERT INTO TBL_SCATEGORY
VALUES
(
SEQ_SCATEGORY.NEXTVAL,
1,
'탄산음료'
);
--
INSERT INTO TBL_STAFF
VALUES
(
SEQ_STAFF.NEXTVAL,
'조지훈',
'010-1234-5678',
DATE '2026-06-25',
'09:00~18:00',
12000,
1
);
--
INSERT INTO TBL_CUSTOMER
VALUES
(
SEQ_CUSTOMER.NEXTVAL,
'홍길동',
'010-9999-9999',
3000,
SYSDATE
);
--
INSERT INTO TBL_EVENT
VALUES
(
SEQ_EVENT.NEXTVAL,
'2+1행사',
DATE '2026-07-01',
DATE '2026-07-31'
);
--
INSERT INTO EVENT_TYPE
VALUES
(
SEQ_EVENT_TYPE.NEXTVAL,
1,
'2+1',
0
);
--
INSERT INTO TBL_PRODUCT
VALUES
(
'P001',
1,
1,
'코카콜라355ml',
'880109401001',
2000,
1200
);
--
INSERT INTO TBL_STOCK
VALUES
(
SEQ_STOCK.NEXTVAL,
'P001',
30
);
--
INSERT INTO TBL_SALE
VALUES
(
SEQ_SALE.NEXTVAL,
1,
1,
SYSDATE
);
--
INSERT INTO TBL_SALE_DETAIL
VALUES
(
SEQ_SALE_DETAIL.NEXTVAL,
'P001',
1,
2,
2000,
0,
'판매완료',
1
);
--
INSERT INTO TBL_PAYMENT
VALUES
(
SEQ_PAYMENT.NEXTVAL,
1,
'결제완료'
);
-- 결제상세
INSERT INTO TBL_PAYMENT_DETAIL
VALUES
(
SEQ_PAYMENT_DETAIL.NEXTVAL,
4000,
0,
0,
4000,
1,
'카드'
);
--
INSERT INTO TBL_ORDER
VALUES
(
'ORD001',
SYSDATE,
'발주완료',
1,
1
);
--
INSERT INTO TBL_ORDER_DETAIL
VALUES
(
SEQ_ORDER_DETAIL.NEXTVAL,
'ORD001',
'P001',
1200,
100
);
--
INSERT INTO TBL_EVENT_PRODUCT
VALUES
(
SEQ_EVENT_PRODUCT.NEXTVAL,
1,
'P001'
);
--
INSERT INTO TBL_STOCK_DETAIL
VALUES
(
SEQ_STOCK_DETAIL.NEXTVAL,
SYSDATE,
'입고',
100,
'최초입고',
DATE '2026-09-30',
1,
1,
'P001'
);
--
INSERT INTO TBL_DISCARD
VALUES
(
SEQ_DISCARD.NEXTVAL,
SYSDATE,
1
);
--
INSERT INTO TBL_DISCARD_DETAIL
VALUES
(
SEQ_DISCARD_DETAIL.NEXTVAL,
1,
'P001',
1
);
--
INSERT INTO TBL_SETTLEMENT
VALUES
(
SEQ_SETTLEMENT.NEXTVAL,
1,
SYSDATE,
100000,
100000,
0
);
--
select *
from tbl_vendor;

-----------------------------------------------------------------------------
---------------------------------------------------
-- 프로젝트 초기화
-- SS25 계정에서 실행
---------------------------------------------------

-- 판매
DROP TABLE TBL_PAYMENT_DETAIL CASCADE CONSTRAINTS;
DROP TABLE TBL_PAYMENT CASCADE CONSTRAINTS;

DROP TABLE TBL_SALE_DETAIL CASCADE CONSTRAINTS;
DROP TABLE TBL_SALE CASCADE CONSTRAINTS;

-- 발주
DROP TABLE TBL_ORDER_DETAIL CASCADE CONSTRAINTS;
DROP TABLE TBL_ORDER CASCADE CONSTRAINTS;

-- 재고
DROP TABLE TBL_STOCK_DETAIL CASCADE CONSTRAINTS;
DROP TABLE TBL_STOCK CASCADE CONSTRAINTS;

-- 행사
DROP TABLE TBL_EVENT_PRODUCT CASCADE CONSTRAINTS;
DROP TABLE EVENT_TYPE CASCADE CONSTRAINTS;
DROP TABLE TBL_EVENT CASCADE CONSTRAINTS;

-- 폐기
DROP TABLE TBL_DISCARD_DETAIL CASCADE CONSTRAINTS;
DROP TABLE TBL_DISCARD CASCADE CONSTRAINTS;

-- 정산
DROP TABLE TBL_SETTLEMENT CASCADE CONSTRAINTS;

-- 상품
DROP TABLE TBL_PRODUCT CASCADE CONSTRAINTS;

-- 분류
DROP TABLE TBL_SCATEGORY CASCADE CONSTRAINTS;
DROP TABLE TBL_MCATEGORY CASCADE CONSTRAINTS;
DROP TABLE TBL_LCATEGORY CASCADE CONSTRAINTS;

-- 기본정보
DROP TABLE TBL_CUSTOMER CASCADE CONSTRAINTS;
DROP TABLE TBL_STAFF CASCADE CONSTRAINTS;
DROP TABLE TBL_JOB CASCADE CONSTRAINTS;
DROP TABLE TBL_VENDOR CASCADE CONSTRAINTS;

-- 조회용
DROP TABLE YEAR_SALES CASCADE CONSTRAINTS;
DROP TABLE MONTH_SALES CASCADE CONSTRAINTS;
DROP TABLE DAY_SALES CASCADE CONSTRAINTS;

---------------------------------------------------
-- Sequence 삭제 (존재하면)
---------------------------------------------------

DROP SEQUENCE SEQ_JOB;
DROP SEQUENCE SEQ_STAFF;
DROP SEQUENCE SEQ_CUSTOMER;
DROP SEQUENCE SEQ_VENDOR;

DROP SEQUENCE SEQ_LCATEGORY;
DROP SEQUENCE SEQ_MCATEGORY;
DROP SEQUENCE SEQ_SCATEGORY;

DROP SEQUENCE SEQ_STOCK;
DROP SEQUENCE SEQ_STOCK_DETAIL;

DROP SEQUENCE SEQ_SALE;
DROP SEQUENCE SEQ_SALE_DETAIL;

DROP SEQUENCE SEQ_PAYMENT;
DROP SEQUENCE SEQ_PAYMENT_DETAIL;

DROP SEQUENCE SEQ_ORDER_DETAIL;

DROP SEQUENCE SEQ_EVENT;
DROP SEQUENCE SEQ_EVENT_PRODUCT;
DROP SEQUENCE SEQ_EVENT_TYPE;

DROP SEQUENCE SEQ_DISCARD;
DROP SEQUENCE SEQ_DISCARD_DETAIL;

DROP SEQUENCE SEQ_SETTLEMENT;

COMMIT;















