show con_name;
ALTER SESSION SET CONTAINER = XEPDB1;
--
CREATE USER ss25
IDENTIFIED BY ss123$;
--
ALTER USER ss25
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP;
--
ALTER USER ss25
QUOTA UNLIMITED ON USERS;
--
GRANT CREATE SESSION TO ss25;
GRANT CREATE TABLE TO ss25;
GRANT CREATE VIEW TO ss25;
GRANT CREATE SEQUENCE TO ss25;
GRANT CREATE SYNONYM TO ss25;
GRANT CREATE PROCEDURE TO ss25;
GRANT CREATE TRIGGER TO ss25;
--
GRANT CONNECT, RESOURCE TO ss25;
--
CONNECT ss25/ss123$@localhost:1521/XEPDB1;
--
SHOW USER;
--
DROP USER ss25 CASCADE;
--
SELECT SYS_CONTEXT('USERENV','SESSION_USER') FROM dual;