show pdbs;
alter session set container = xepdb1;
show con_name;
CREATE USER SS25 IDENTIFIED BY ss123$;
ALTER USER SS25
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP;
ALTER USER SS25
QUOTA UNLIMITED ON USERS;
GRANT CONNECT, RESOURCE TO SS25;
GRANT CREATE VIEW TO SS25;
GRANT CREATE SEQUENCE TO SS25;
GRANT CREATE SYNONYM TO SS25;
GRANT CREATE TRIGGER TO SS25;