-- 데이터 임포트순서
TBL_JOB
TBL_LCATEGORY
TBL_MCATEGORY
TBL_SCATEGORY
TBL_VENDOR
TBL_CUSTOMER
TBL_STAFF
TBL_EVENT
TBL_EVENT_TYPE
TBL_PRODUCT
TBL_STOCK
TBL_STOCK_DETAIL
TBL_ORDER
TBL_ORDER_DETAIL
TBL_SALE
TBL_SALE_DETAIL
TBL_PAYMENT
--TBL_PAYMENT_DETAIL -> PAY_METHOD VARCHAR2(20)
TBL_DISCARD
TBL_DISCARD_DETAIL
TBL_SETTLEMENT