-- 시나리오 
--환불 전 영수증 조회
--UP_REFUND('SA001','ST001') 실행
--PAYMENT 확인
--SALE_DETAIL 확인
--STOCK 확인
--영수증 다시 조회(환불 영수증 출력)
--같은 판매번호로 다시 실행 → ORA-20001 발생 시연

-- 현재 SA001, 002 로 연습

--1)
SELECT *
FROM TBL_PAYMENT
WHERE SALE_ID='SA002';
--
SELECT PD.*
FROM TBL_PAYMENT_DETAIL PD
JOIN TBL_PAYMENT P
ON PD.PAY_DETAIL_ID=P.PAY_DETAIL_ID
WHERE P.SALE_ID='SA002';
--
SELECT *
FROM TBL_SALE_DETAIL
WHERE SALE_ID='SA002'
ORDER BY SALE_DETAIL_ID;
--상품번호1,3,9 현재재고 35,18,48
SELECT *
FROM TBL_STOCK
WHERE PRODUCT_CODE IN
(
    SELECT PRODUCT_CODE
    FROM TBL_SALE_DETAIL
    WHERE SALE_ID='SA002'
);
--
SELECT *
FROM TBL_STOCK_DETAIL
WHERE PRODUCT_CODE IN
(
    SELECT PRODUCT_CODE
    FROM TBL_SALE_DETAIL
    WHERE SALE_ID='SA002'
)
ORDER BY STOCK_DETAIL_CODE;
-- 프로시져 실행
EXEC UP_REFUND('SA002');
-- 재실행 (사용자 예외처리 검증)
BEGIN
    UP_REFUND('SA002');
END;
/

--
show errors;
--
SELECT LINE,
       POSITION,
       TEXT
FROM USER_ERRORS
WHERE NAME = 'UP_REFUND'
ORDER BY SEQUENCE;