-- 결제번호 시퀀스
CREATE SEQUENCE SEQ_PAYMENT
START WITH 71
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- 결제상세번호 시퀀스
CREATE SEQUENCE SEQ_PAYMENT_DETAIL
START WITH 101
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- 판매상세번호 시퀀스
CREATE SEQUENCE SEQ_SALE_DETAIL
START WITH 201
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- 재고상세번호 시퀀스
CREATE SEQUENCE SEQ_STOCK_DETAIL
START WITH 201
INCREMENT BY 1
NOCACHE
NOCYCLE;
-- 
-----------------시퀀스 사용 x--------------------------------------
/*
    함수명 : UF_NEXT_PAYMENT

    작성자 : 조지훈

    기능
    - PAYMENT PK 생성
    - 현재 가장 큰 PAY_DETAIL_ID를 찾아 다음 번호를 반환한다.

    예)
    PA001
    PA002
    ...
*/

CREATE OR REPLACE FUNCTION UF_NEXT_PAYMENT
RETURN VARCHAR2
IS
    V_NEXT_NO NUMBER;
BEGIN

    SELECT NVL(MAX(TO_NUMBER(SUBSTR(PAY_DETAIL_ID,3))),0)+1
    INTO V_NEXT_NO
    FROM TBL_PAYMENT;

    RETURN 'PA' || LPAD(V_NEXT_NO,3,'0');

END;
/
/*
    PAYMENT_DETAIL PK 생성
*/

CREATE OR REPLACE FUNCTION UF_NEXT_PAYMENT_DETAIL
RETURN VARCHAR2
IS
    V_NEXT_NO NUMBER;
BEGIN

    SELECT NVL(MAX(TO_NUMBER(SUBSTR(PAY_DETAIL_NUMBER,4))),0)+1
    INTO V_NEXT_NO
    FROM TBL_PAYMENT_DETAIL;

    RETURN 'PAD' || LPAD(V_NEXT_NO,3,'0');

END;
/
/*
    SALE_DETAIL PK 생성
*/

CREATE OR REPLACE FUNCTION UF_NEXT_SALE_DETAIL
RETURN VARCHAR2
IS
    V_NEXT_NO NUMBER;
BEGIN

    SELECT NVL(MAX(TO_NUMBER(SUBSTR(SALE_DETAIL_ID,4))),0)+1
    INTO V_NEXT_NO
    FROM TBL_SALE_DETAIL;

    RETURN 'SAD' || LPAD(V_NEXT_NO,3,'0');

END;
/

/*
    STOCK_DETAIL PK 생성
*/

CREATE OR REPLACE FUNCTION UF_NEXT_STOCK_DETAIL
RETURN VARCHAR2
IS
    V_NEXT_NO NUMBER;
BEGIN

    SELECT NVL(MAX(TO_NUMBER(SUBSTR(STOCK_DETAIL_CODE,3))),0)+1
    INTO V_NEXT_NO
    FROM TBL_STOCK_DETAIL;

    RETURN 'SD' || LPAD(V_NEXT_NO,3,'0');

END;
/

